# Generated by Django 3.0.4 on 2021-09-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('children', models.IntegerField()),
                ('sex_female', models.IntegerField()),
                ('sex_male', models.IntegerField()),
                ('smoke_no', models.IntegerField()),
                ('smoke_yes', models.IntegerField()),
                ('charges', models.FloatField()),
            ],
        ),
    ]
