# Generated by Django 3.0.4 on 2021-09-20 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predresults',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='children',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='sex_female',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='sex_male',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='smoke_no',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='smoke_yes',
        ),
    ]
