# Generated by Django 3.0.4 on 2021-09-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0002_auto_20210920_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='predresults',
            name='charges',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='predresults',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predresults',
            name='sex_female',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predresults',
            name='sex_male',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='predresults',
            name='smoke_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predresults',
            name='smoke_yes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='bmi',
            field=models.FloatField(default=22.0),
        ),
    ]
